const One = [
    "Citizen Kane",
    "The Godfather",
    "Casablanca",
    "Raging Bull",
    "Singin' in the Rain",
    "Gone with the Wind",
    "Lawrence of Arabia",
    "Schindler's List",
    "Vertigo",
    "The Wizard of Oz",
    "City Lights",
    "The Searchers",
    "Star Wars Episode IV: A New Hope",
    "Psycho",
    "2001: A Space Odyssey",
    "The Graduate",
    "The General",
    "On the Waterfront",
    "It's a Wonderful Life",
    "Chinatown",
    "Some Like It Hot",
    "The Grapes of Wrath",
    "E.T. the Extra-Terrestrial",
    "To Kill a Mockingbird",
    "Mr. Smith Goes to Washington",
    "High Noon",
    "Wayne's World",
    "All About Eve",
    "Double Indemnity",
    "Apocalypse Now",
    "The Maltese Falcon",
    "The Godfather Part II",
    "One Flew Over the Cuckoo's Nest",
    "Snow White and the Seven Dwarfs",
    "Annie Hall",
    "The Bridge on the River Kwai",
    "The Best Years of Our Lives",
    "The Treasure of the Sierra Madre",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "The Sound of Music",
    "Bonnie and Clyde",
    "Midnight Cowboy",
    "The Philadelphia Story",
    "Shane",
    "It Happened One Night",
    
]

const Two = [
    "A Streetcar Named Desire",
    "Rear Window",
    "Intolerance",
    "The Lord of the Rings: The Fellowship of the Ring",
    "West Side Story",
    "Taxi Driver",
    "The Deer Hunter",
    "MASH",
    "North by Northwest",
    "Jaws",
    "Rocky",
    "The Gold Rush",
    "Nashville",
    "Duck Soup",
    "Sullivan's Travels",
    "American Graffiti",
    "Cabaret",
    "Network",
    "The African Queen",
    "Raiders of the Lost Ark",
    "Who's Afraid of Virginia Woolf?",
    "Unforgiven",
    "Tootsie",
    "A Clockwork Orange",
    "Saving Private Ryan",
    "The Shawshank Redemption",
    "Butch Cassidy and the Sundance Kid",
    "The Silence of the Lambs",
    "In the Heat of the Night",
    "Forrest Gump",
    "All the President's Men",
    "Modern Times",
    "The Wild Bunch",
    "The Apartment",
    "Spartacus",
    "Titanic",
    "Easy Rider",
    "A Night at the Opera",
    "Platoon",
    "12 Angry Men",
    "Bringing Up Baby",
    "The Sixth Sense",
    "Swing Time",
    "Sophie's Choice",
    "GoodFellas",
    "The French Connection",
    "Pulp Fiction",
    "The Last Picture Show",
    "Do the Right Thing",
    "Blade Runner",
    "Yankee Doodle Dandy",
    "Toy Story",
    "Ben-Hur",
    "Dead Man's Shoes"
]

const Three = [
    "Jackie Brown",
    "Batman Begins",
    "The Rock",
    "Jumanji",
    "Toy Story 2",
    "Blow",
    "Tinker Tailor Soldier Spy",
    "Avatar",
    "The Black Cauldron",
    "Little Miss Sunshine",
    "This is England",
    "The Truman Show",
    "Pillow Talk",
    "The Deaprted",
    "The Bourne Identity",
    "Tron",
    "The Death of Stalin",
    "Get Out",
    "Hook",
    "This is Spinal Tap",
    "Parasite",
    "Elf",
    "Sister Act",
    "Wahtever Happened to Baby Jane?",
    "You've Got Mail",
    "Beverly Hills Cop",
    "Catch Me if you Can",
    "Notting Hill",
    "Time Bandits",
    "Halloween",
    "Batman Forever",
    "Donnie Darko",
    "The Killing Fields",
    "Philadelphia",
    "Life of Brian",
    "Shutter Island",
    "Manchester by the sea",
    "South Park: Bigger, Longer & Uncut",
    "Eraserhead",
    "An American Werewolf in London"
]

const Four = [
    "The Wicker Man",
    "The Third Man",
    "Pearl Harbor",
    "Harry Potter and the Prisoner of Azkaban",
    "Gone in 60 seconds",
    "Tropic Thunder",
    "Iron Man",
    "The Fugitive",
    "A Few Good Men",
    "Deliverance",
    "Inception",
    "Dog Day Afternoon",
    "Into the Wild",
    "Scarface",
    "Heavenly Creatures",
    "Along Came a Spider",
    "Mrs Doubtfire",
    "Midnight Run",
    "Bridget Jones's Diary",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Casino Royale",
    "Basic Instinct",
    "Marathon Man",
    "Pretty Woman",
    "Independence Day",
    "Sin City",
    "Die Hard",
    "Sleepy Hollow",
    "Once Upon a time in America",
    "Road House",
    "Sideways",
    "Waterworld",
    "In the name of the father",
    "The Dark Knight",
    "Lethal Weapon",
    "Breakfast at Tiffany's",
    "Anchorman: The Legend of Ron Burgundy",
    "Honey, I Shrunk the Kids",
    "Pan's Labyrinth",
    "Grease",
    "Gladiator"
]

const Five = [
    "Bridesmaids",
    "Dirty Dancing",
    "Indecent Proposal",
    "Blue Velvet",
    "Terminator 2: Judgment Day",
    "Shaun of the Dead",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Airplane",
    "The Naked Gun",
    "Home Alone",
    "The Breakfast Club",
    "When Harry met Sally",
    "Mean Streets",
    "The Mask",
    "What's eating Gilbert Grape",
    "The wolf of wall street",
    "Any given sunday",
    "She's all that",
    "The Sting",
    "Cool Hand Luke",
    "The Artist",
    "Apollo 13",
    "The Devil Wears Prada",
    "Barton Fink",
    "Chitty Chitty Bang Bang",
    "Zulu",
    "Mary Poppins",
    "Mean Girls",
    "The Color Purple",
    "Amadeus",
    "Reversal of Fortune",
    "Enemy of the State",
    "Good Will Hunting",
    "Legally Blonde",
    "Boogie Nights",
    "Trainspotting",
    "GoldenEye",
    "In the Loop",
    "Dazed and Confused",
    "Weekend at Bernie's",
    "Beverly Hills Cop II",
    "Shrek",
    "Risky Business"
]

const Six = [
    "The King's Speech",
    "Rogue One: A Star Wars Story",
    "Falling Down",
    "The Talented Mr Ripley",
    "Harry Potter and the Order of the Phoenix",
    "Kramer vs Kramer",
    "Logan's Run",
    "Austin Powers: International Man of Mystery",
    "Picnic on hanging rock",
    "The Adventures of Priscilla, Queen of the Desert",
    "The Matrix",
    "Bad Boys",
    "The Piano",
    "The elephant man",
    "Batman",
    "The Goonies",
    "Roman Holiday",
    "Mulholland Drive",
    "Starship Troopers",
    "50 shades of grey",
    "The Muppet Christmas Carol",
    "American Pie",
    "The jazz singer",
    "An American Tail",
    "Four Weddings and a Funeral",
    "Days of Thunder",
    "Serpico",
    "Manhunter",
    "The fifth element",
    "Indiana Jones and the Temple of Doom",
    "The Thing",
    "Primal Fear",
    "Monty Python and the Holy Grail",
    "Knives Out",
    "The Good, the Bad and the Ugly",
    "The Birds",
    "The Omen",
    "The Blair Witch Project",
    "As Good as it gets",
    "Absolute Beginners"

]

export {One, Two, Three, Four, Five, Six}

