const One = [
    "Citizen Kane",
    "The Godfather",
    "Casablanca",
    "Raging Bull",
    "Singin' in the Rain",
    "Gone with the Wind",
    "Lawrence of Arabia",
    "Schindler's List",
    "Vertigo",
    "The Wizard of Oz",
    "City Lights",
    "The Searchers",
    "Star Wars Episode IV: A New Hope",
    "Psycho",
    "2001: A Space Odyssey",
    "The Graduate",
    "The General",
    "On the Waterfront",
    "Straw Dogs",
    "The Damned United",
    "V for Vendetta",
    "A Hard Day's Night",
    "10 things i hate about you",
    "It's a Wonderful Life",
    "Chinatown",
    "Some Like It Hot",
    "The Grapes of Wrath",
    "E.T. the Extra-Terrestrial",
    "To Kill a Mockingbird",
    "Mr. Smith Goes to Washington",
    "Mutiny on the Bounty",
    "Way of the Dragon",
    "Mystic Pizza",
    "Into the Wild",
    "High Noon",
    "Wayne's World",
    "All About Eve",
    "Double Indemnity",
    "Apocalypse Now",
    "The Maltese Falcon",
    "The Godfather Part II",
    "One Flew Over the Cuckoo's Nest",
    "Hot Fuzz",
    "The Lincoln Lawyer",
    "Little Shop of Horrors",
    "Snow White and the Seven Dwarfs",
    "Annie Hall",
    "The Bridge on the River Kwai",
    "The Best Years of Our Lives",
    "The Treasure of the Sierra Madre",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "The Sound of Music",
    "Bonnie and Clyde",
    "Midnight Cowboy",
    "Now Voyager",
    "Edward Scissorhands",
    "Men in Black",
    "Fantasia",
    "The Philadelphia Story",
    "Shane",
    "It Happened One Night",
    
]

const Two = [
    "A Streetcar Named Desire",
    "Rear Window",
    "Intolerance",
    "The Lord of the Rings: The Fellowship of the Ring",
    "West Side Story",
    "Taxi Driver",
    "The Deer Hunter",
    "MASH",
    "North by Northwest",
    "Jaws",
    "Rocky",
    "The Gold Rush",
    "Nashville",
    "Duck Soup",
    "Sullivan's Travels",
    "American Graffiti",
    "Cabaret",
    "Network",
    "The African Queen",
    "Raiders of the Lost Ark",
    "Who's Afraid of Virginia Woolf?",
    "Unforgiven",
    "Tootsie",
    "A Clockwork Orange",
    "Saving Private Ryan",
    "The Shawshank Redemption",
    "Armageddon",
    "Alien",
    "Brokeback Mountain",
    "Braveheart",
    "Butch Cassidy and the Sundance Kid",
    "The Silence of the Lambs",
    "In the Heat of the Night",
    "Forrest Gump",
    "All the President's Men",
    "Modern Times",
    "The Wild Bunch",
    "The Apartment",
    "Spartacus",
    "Titanic",
    "Easy Rider",
    "A Night at the Opera",
    "Platoon",
    "12 Angry Men",
    "The Patriot",
    "The Lord of the Rings: The Two Towers",
    "Bringing Up Baby",
    "The Sixth Sense",
    "Swing Time",
    "Sophie's Choice",
    "How to lose a guy in 10 days",
    "GoodFellas",
    "The French Connection",
    "Pulp Fiction",
    "The Last Picture Show",
    "Do the Right Thing",
    "Blade Runner",
    "Yankee Doodle Dandy",
    "Toy Story",
    "Ben-Hur",
    "Dead Man's Shoes"
]

const Three = [
    "Jackie Brown",
    "Batman Begins",
    "The Rock",
    "Jumanji",
    "Toy Story 2",
    "Blow",
    "Tinker Tailor Soldier Spy",
    "Avatar",
    "The Black Cauldron",
    "Little Miss Sunshine",
    "This is England",
    "The Truman Show",
    "Pillow Talk",
    "The Departed",
    "The Bourne Identity",
    "Tron",
    "The Death of Stalin",
    "Get Out",
    "Hook",
    "This is Spinal Tap",
    "Parasite",
    "Elf",
    "Sister Act",
    "Whatever Happened to Baby Jane?",
    "You've Got Mail",
    "Beverly Hills Cop",
    "Catch Me if you Can",
    "Notting Hill",
    "Time Bandits",
    "Halloween",
    "Batman Forever",
    "Donnie Darko",
    "The Killing Fields",
    "Philadelphia",
    "Life of Brian",
    "Shutter Island",
    "Manchester by the sea",
    "South Park: Bigger, Longer & Uncut",
    "Eraserhead",
    "An American Werewolf in London",
    "Harry Potter & the chamber of secrets",
    "Batman Returns",
    "Uncle Buck",
    "Predator",
    "8 Mile",
    "Clueless",
    "Bill & Ted's Excellent Adventure",
    "The Avengers",
    "The Incredibles",
    "Foxcatcher",
    "Animal House",
    "Mississippi Burning",
    "Full Metal Jacket",
    "The Wild One",
    "Bernie",
    "School of Rock",
    "White Men Can't Jump",
    "In Brugges",
    "Brazil",
    "Snatch",
    "The Commitments",
    "Manhatten",

]

const Four = [
    "The Wicker Man",
    "The Third Man",
    "Pearl Harbor",
    "Harry Potter and the Prisoner of Azkaban",
    "Gone in 60 seconds",
    "Tropic Thunder",
    "Iron Man",
    "The Fugitive",
    "A Few Good Men",
    "Deliverance",
    "Inception",
    "Dog Day Afternoon",
    "Into the Wild",
    "Scarface",
    "Heavenly Creatures",
    "Along Came a Spider",
    "Mrs Doubtfire",
    "Midnight Run",
    "Bridget Jones's Diary",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Casino Royale",
    "Basic Instinct",
    "Marathon Man",
    "Pretty Woman",
    "Independence Day",
    "Sin City",
    "Die Hard",
    "Sleepy Hollow",
    "Once Upon a time in America",
    "Road House",
    "Sideways",
    "Waterworld",
    "In the name of the father",
    "The Dark Knight",
    "Lethal Weapon",
    "Breakfast at Tiffany's",
    "Anchorman: The Legend of Ron Burgundy",
    "Honey, I Shrunk the Kids",
    "Pan's Labyrinth",
    "Grease",
    "Gladiator",
    "Gone Baby Gone",
    "Walk the line",
    "Back to the Future Part II",
    "Best in Show",
    "Ocean's Eleven",
    "Clerks",
    "Das Boot",
    "Slumdog Millionaire",
    "Star Wars: Episode III - Revenge of the Sith",
    "East is East",
    "Saturday Night Fever",
    "The Exorcist",
    "Badlands",
    "Carrie",
    "Ferris Bueller's Day off",
    "The Conversation",
    "Invasion of the Body Snatchers",
    "Rush",
    "Rocky III",
    "Field of Dreams",
    "O Lucky Man",
    "The Bodyguard"
]

const Five = [
    "Bridesmaids",
    "Dirty Dancing",
    "Indecent Proposal",
    "Blue Velvet",
    "Terminator 2: Judgment Day",
    "Shaun of the Dead",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Airplane",
    "The Naked Gun",
    "Home Alone",
    "The Breakfast Club",
    "When Harry met Sally",
    "Mean Streets",
    "The Mask",
    "What's eating Gilbert Grape",
    "The wolf of wall street",
    "Any given sunday",
    "She's all that",
    "The Sting",
    "Cool Hand Luke",
    "The Artist",
    "Apollo 13",
    "The Devil Wears Prada",
    "Barton Fink",
    "Chitty Chitty Bang Bang",
    "Zulu",
    "Mary Poppins",
    "Mean Girls",
    "The Color Purple",
    "Amadeus",
    "Reversal of Fortune",
    "Enemy of the State",
    "Good Will Hunting",
    "Legally Blonde",
    "Boogie Nights",
    "Trainspotting",
    "GoldenEye",
    "In the Loop",
    "Dazed and Confused",
    "Weekend at Bernie's",
    "Beverly Hills Cop II",
    "Shrek",
    "Risky Business",
    "The Wrestler",
    "Deep Impact",
    "Live and Let Die",
    "Dr. No",
    "Withnail & I",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Kes",
    "Cast Away",
    "X-Men: First Class",
    "Jacob's Ladder",
    "The Little Mermaid",
    "Aliens",
    "Love Actually",
    "Groundhog Day",
    "Caddyshack",
    "The Big Lebowski",
    "Gravity",
    "Kill Bill",
    "Beethoven",
    "The Fly",
    "Thelma & Louise",
]

const Six = [
    "The King's Speech",
    "Rogue One: A Star Wars Story",
    "Falling Down",
    "The Talented Mr Ripley",
    "Harry Potter and the Order of the Phoenix",
    "Kramer vs Kramer",
    "Logan's Run",
    "Austin Powers: International Man of Mystery",
    "Picnic at hanging rock",
    "The Adventures of Priscilla, Queen of the Desert",
    "The Matrix",
    "Bad Boys",
    "The Piano",
    "The elephant man",
    "The Witches",
    "The Goonies",
    "Roman Holiday",
    "Mulholland Drive",
    "Starship Troopers",
    "Fifty shades of grey",
    "The Muppet Christmas Carol",
    "American Pie",
    "The jazz singer",
    "An American Tail",
    "Four Weddings and a Funeral",
    "Days of Thunder",
    "Serpico",
    "Manhunter",
    "The fifth element",
    "Indiana Jones and the Temple of Doom",
    "The Thing",
    "Primal Fear",
    "Monty Python and the Holy Grail",
    "Knives Out",
    "The Good, the Bad and the Ugly",
    "The Birds",
    "The Omen",
    "The Blair Witch Project",
    "As Good as it gets",
    "Absolute Beginners",
    "The Ipcress File",
    "Educating Rita",
    "101 Dalmatians",
    "Ace Ventura: Pet Detective",
    "City of God",
    "Interstellar",
    "The Terminator",
    "Whiplash",
    "The Prestige",
    "THe Usual Suspects",
    "Indiana Jones and the Raiders of the Lost Ark",
    "WALL-E",
    "The Shining",
    "The Great Dictator",
    "Requiem for a Dream",
    "Star Wars: Episode VI - Return of the Jedi",
    "Blazing Saddles",
    "Eternal Sunshine of the Spotless Mind",
    "Reservoir Dogs",
    "Amélie",
    "Metropolis",
    "Downfall",
    "There will be blood",
    "The Great Escape"
]

const Seven = [
    "Fatal Attraction",
    "The Matrix Reloaded",
    "The Long Good Friday",
    "Who Framed Roger Rabbit",
    "Mildred Pierce",
    "Hostel",
    "Saw",
    "Scream",
    "Speed",
    "Demolition Man",
    "Spotlight",
    "The Hurt Locker",
    "Out of Africa",
    "The Shape of Water",
    "Gandhi",
    "My Fair Lady",
    "The Adventures of Robin Hood",
    "Robin Hood: Prince of Thieves",
    "The Princess Bride",
    "Lethal Weapon 2",
    "Mad Max: Fury Road",
    "The English Patient",
    "Heathers",
    "True Romance",
    "Django Unchained",
    "Sphere",
    "Crash",
    "Showgirls",
    "Austin Powers: The Spy who shagged me",
    "Uncut Gems",
    "Big Night",
    "Precious",
    "The Irishman",
    "The Godfather part III",
    "The Lion king",
    "Aladdin",
    "La Haine",
    "9 to 5",
    "The Muppet Movie",
    "Memento",
    "The Lives of Others",
    "Team America: World Police",
    "Fame",
    "Born Free",
    "Free Willy",
    "Tremors",
    "Hsckers",
    "Nil by Mouth",
    "The Hunt for Red October",
    "Training Day",
    "Minority Report",
    "Planes, Trains & Automobiles",
    "Con Air",
    "A Fish Called Wanda",
    "Jurassic Park",
    "Bedknobs and Broomsticks",
    "Election",
    "The King of Comedy",
    "Footloose",
    "Frost/Nixon",
    "My Dinner with Andre",
    "The Poseidon Adventure",
    "The Post",
    "Coming to America"

]

const Eight = [
    "Children of Men",
    "Of Mice and Men",
    "Kingsman: The Secret Service",
    "Dawn of the Dead",
    "The Evil Dead",
    "Donnie Brasco",
    "The Mummy",
    "Liar Liar",
    "Dances with Wolves",
    "The Madness of King George",
    "Get Carter",
    "Batman vs Superman",
    "The Santa Clause",
    "Toy Story 3",
    "High Fidelity",
    "Pretty in Pink",
    "The Full Monty",
    "Erin Brockovich",
    "L.A. Confidential",
    "Wonder Woman",
    "Birdman",
    "Black Swan",
    "Trading Places",
    "Skyfall",
    "Brassed Off",
    "Secrets & Lies",
    "Monsters Inc",
    "Secretary",
    "Van Helsing",
    "Casino",
    "Alfie",
    "The lego movie",
    "Rambo: First Blood",
    "Son of Rambow",
    "First Blood",
    "The Expendables",
    "Star Wars: Episode I - The Phantom Menace",
    "The Horse Whisperer",
    "American Beauty",
    "Sense and Sensibility",
    "Guess Who's Coming to Dinner",
    "The Room",
    "The Disaster Artist",
    "Fargo",
    "Leaving Las Vegas",
    "Glengarry Glen Ross",
    "My Left Foot",
    "Dodgeball: A True Underdog Story",
    "La La Land",
    "Doctor Zhivago",
    "12 Monkeys",
    "The Lost Boys",
    "Hugo",
    "The Karate Kid",
    "Paths of Glory",
    "Fight Club",
    "Rebecca",
    "Se7en",
    "Seven Samurai",
    "The Revenant",
    "A Beautiful Mind",
    "Face/Off",
    "Snakes on a plane",
    "Point Break",
    "Don't Look Now"
]

const Nine = [
    "The Lord of the Rings: The Return of the King",
    "Beetlejuice",
    "Nosferatu",
    "Thor",
    "Fitzcarraldo",
    "Aguirre, the Wrath of God",
    "Ghostbusters",
    "The Cider House Rules",
    "Beauty & the Beast",
    "Molly's Game",
    "On Her Majesty's Secret Service",
    "Breathless",
    "Joker",
    "The Fighter",
    "Romy and Michele's High School Reunion",
    "Home Alone 2: Lost in New York",
    "Meet the Parents",
    "Total Recall",
    "The Dark Knight Rises",
    "The Towering Inferno",
    "Flash Gordon",
    "Black Hawk Down",
    "Rosemary's Baby",
    "Kick-Ass",
    "Lock, Stock and Two Smoking Barrels",
    "The Big Short",
    "The Nutty Professor",
    "South Pacific",
    "The Hunger Games",
    "The Lost World: Jurassic Park",
    "Punch Drunk Love",
    "Happy Gilmore",
    "The Mighty Ducks",
    "Scum",
    "The Blues Brothers",
    "The Iron Lady",
    "Twilight",
    "Watership Down",
    "Inside Man",
    "Malcolm X",
    "Blood Diamond",
    "Ronin",
    "Planet of the Apes",
    "Bowling for Columbine",
    "Super Size Me",
    "Nixon",
    "JFK",
    "The Untouchables",
    "The Jerk",
    "Father of the Bride",
    "Out of Sight",
    "Being John Malkovich",
    "Mission Impossible 2",
    "Nightmare of Elm Street",
    "That thing you do",
    "Die Hard 2",
    "Tomorrow Never Dies",
    "Signs",
    "The Princess Diaries",
    "Chariots of Fire",
    "Empire of the Sun",
    "American Psycho",
    "Galaxy Quest",
    "The Royal Tenenbaums"



]

export {One, Two, Three, Four, Five, Six, Seven, Eight, Nine}

